/** an object with the default values that come when loading the app. */
export const emptyInvoice = {
    logo: '',
    history: false,
    from: '',
    to: '',    
    ship_to: undefined,
    number: 2,
    purchase_order: '',
    date_format: '',
    date: new Date(),
    payment_terms: '',
    currency: {value : "$" , label : "USD ($)"},
    discounts: '',
    tax: '',
    shipping: 0,
    amount_paid: 0,
    notes: '',
    terms: '',
    header: "INVOICE",
    to_title: "Bill To",
    ship_to_title : "Ship To",
    date_title : "Date",
    payment_terms_title : "Payment Terms",
    due_date_title : "Due Date",
    purchase_order_title : "PO Number",
    item_header : "Item",
    items : [{
        quantity: 0,
        name: "",
        description: "",
        unit_cost: 0,
        amount: 0,
        index: 0
    }],
    quantity_header : "Quantity",
    unit_cost_header : "Rate",
    amount_header : "Amount",
    subtotal_title : "Subtotal",
    discounts_title : "Discount",
    tax_title : "Tax",
    shipping_title : "Shipping",
    total_title : "Total",
    amount_paid_title : "Amount Paid",
    balance_title : "Balance Due",
    terms_title : "Terms",
    notes_title : "Notes",
    id: 1,
    subtotal: 0,
    total: 0,
    balance: 0
}